const loadData = {
  result: [
    { key: 21469, title: "BB Leads Networks", isBranch: true, children: [] },
    {
      key: 22031,
      title: "NW Closed Pnp & Boxer Branches",
      isBranch: true,
      children: [],
    },
    { key: 22033, title: "NW Pool", isBranch: true, children: [] },
    { key: 22425, title: "Northern", isBranch: true, children: [] },
    { key: 22426, title: "Southern", isBranch: true, children: [] },
    {
      key: 2812,
      title: "Glen (Finance) van Niekerk",
      isBranch: false,
      children: [],
    },
    {
      key: 2925,
      title: "Elelwani  (NREB) Pandelani",
      isBranch: false,
      children: [],
    },
    {
      key: 3141,
      title: "Christa (Risk) Van Der Walt",
      isBranch: false,
      children: [],
    },
    {
      key: 3206,
      title: "Craig (Marketing) Minnie",
      isBranch: false,
      children: [],
    },
    {
      key: 3230,
      title: "Thirusha (L&D) Pillay",
      isBranch: false,
      children: [],
    },
    {
      key: 3238,
      title: "Hester (Branch) Barnes",
      isBranch: false,
      children: [],
    },
    {
      key: 3248,
      title: "Zulmira (Projects) Cabula",
      isBranch: false,
      children: [],
    },
    { key: 3442, title: "Kim (PRB) Koch", isBranch: false, children: [] },
    {
      key: 3560,
      title: "Ludie (RRB) Pretoriuss",
      isBranch: false,
      children: [],
    },
    {
      key: 3775,
      title: "Ilse (distribution) De Graaf",
      isBranch: false,
      children: [],
    },
    { key: 3819, title: "Johan (Risk) Moerdyk", isBranch: false, children: [] },
    {
      key: 3893,
      title: "Tiisetso (C&R) Maishoane   (Risk Monitoring)",
      isBranch: false,
      children: [],
    },
    {
      key: 4031,
      title: "Premeshni (BSM) Kistasamy",
      isBranch: false,
      children: [],
    },
    {
      key: 4054,
      title: "Phumlani (BIS) Mkhonza",
      isBranch: false,
      children: [],
    },
    {
      key: 4633,
      title: "Portia (Finance) Tsoaledi",
      isBranch: false,
      children: [],
    },
    {
      key: 4707,
      title: "Tapiwa (Research and Client Insights) Mkombe",
      isBranch: false,
      children: [],
    },
    { key: 4794, title: "Linda (PGM) Mbambo", isBranch: false, children: [] },
    { key: 4972, title: "Anneri Visser", isBranch: false, children: [] },
    {
      key: 5170,
      title: "Arion (Digital) Hendricks",
      isBranch: false,
      children: [],
    },
    {
      key: 5199,
      title: "Malatsi (MI) Mamphetho",
      isBranch: false,
      children: [],
    },
    {
      key: 5280,
      title: "June (Finance) Hansraj",
      isBranch: false,
      children: [],
    },
    { key: 5334, title: "Reratilwe (RRB) Moje", isBranch: false, children: [] },
    {
      key: 5615,
      title: "Madeleen (NIC) Bester",
      isBranch: false,
      children: [],
    },
    {
      key: 5749,
      title: "Queen (Process) Phechudi",
      isBranch: false,
      children: [],
    },
    { key: 5869, title: "Mpho (MIS) Rangoako", isBranch: false, children: [] },
    {
      key: 5891,
      title: "Natalie (MFC) van Staden",
      isBranch: false,
      children: [],
    },
    {
      key: 5900,
      title: "Christine (OPS) Fourie",
      isBranch: false,
      children: [],
    },
    { key: 6114, title: "Reyhana(BSM) Wadee", isBranch: false, children: [] },
    { key: 6266, title: "Jaco (MIS) Robbertse", isBranch: false, children: [] },
    { key: 6281, title: "Nadia Harrikaran", isBranch: false, children: [] },
    { key: 6341, title: "Nnana (Card) Mdaka", isBranch: false, children: [] },
    {
      key: 6366,
      title: "Sedick (Risk)  Rylands",
      isBranch: false,
      children: [],
    },
    { key: 6407, title: "Melissa (TIP) Haupt", isBranch: false, children: [] },
    { key: 6718, title: "Darshna (Card) Nana", isBranch: false, children: [] },
    {
      key: 6838,
      title: "Charlene (RRB) Jacobs",
      isBranch: false,
      children: [],
    },
    { key: 6889, title: "Keri (MI) Parmaswar", isBranch: false, children: [] },
    {
      key: 6991,
      title: "Yazel(PL - RSM) Hassein",
      isBranch: false,
      children: [],
    },
    { key: 7015, title: "Tia (C&R) Smook", isBranch: false, children: [] },
    { key: 7031, title: "Sonia (Risk) Naka", isBranch: false, children: [] },
    {
      key: 7320,
      title: "Ansa  (Sales Effectiveness) Swart",
      isBranch: false,
      children: [],
    },
    { key: 7375, title: "Amelia (CE) Botha", isBranch: false, children: [] },
    { key: 7386, title: "Paul (L&D) Ullbricht", isBranch: false, children: [] },
    {
      key: 9494,
      title: "Tsibiso (MIS) Mmabane",
      isBranch: false,
      children: [],
    },
    {
      key: 9814,
      title: "Hugo (Sales Champ) Troskie",
      isBranch: false,
      children: [],
    },
    {
      key: 9880,
      title: "Lerato (compliance) Aphane",
      isBranch: false,
      children: [],
    },
    { key: 9890, title: "Riaan Van Rooi", isBranch: false, children: [] },
    { key: 10349, title: "Ismail (MI) Makra", isBranch: false, children: [] },
    {
      key: 10392,
      title: "Siphindile (MIS) Soni",
      isBranch: false,
      children: [],
    },
    {
      key: 11020,
      title: "Corrine (RRB) Naidoo",
      isBranch: false,
      children: [],
    },
    { key: 11156, title: "Slade (NIC) Bergoff", isBranch: false, children: [] },
    {
      key: 11297,
      title: "Jason (NSM Consumer) Barron",
      isBranch: false,
      children: [],
    },
    {
      key: 11310,
      title: "Vincent (Branch) Banks",
      isBranch: false,
      children: [],
    },
    { key: 11347, title: "Cliff (CE) Joseph", isBranch: false, children: [] },
    { key: 11527, title: "Cindy  Fourie", isBranch: false, children: [] },
    { key: 11604, title: "John (TIP) Venter", isBranch: false, children: [] },
    {
      key: 11621,
      title: "Kalay (Nedlife) Hassan",
      isBranch: false,
      children: [],
    },
    {
      key: 11654,
      title: "Jaco (Marketing) Swart",
      isBranch: false,
      children: [],
    },
    {
      key: 14284,
      title: "Boitumelo (MIS) Molelekeng",
      isBranch: false,
      children: [],
    },
    {
      key: 14301,
      title: "Kagiso (Distribution) Sithole",
      isBranch: false,
      children: [],
    },
    {
      key: 14352,
      title: "Lungile (RRB Sales&Retention) Maswili",
      isBranch: false,
      children: [],
    },
    { key: 14419, title: "Viresh (MIS) Singh", isBranch: false, children: [] },
    { key: 14839, title: "Trevor (NIC) Lobban", isBranch: false, children: [] },
    {
      key: 15793,
      title: "Valma (Operations) Raam",
      isBranch: false,
      children: [],
    },
    {
      key: 15836,
      title: "Zohra (Internal Audit) Mahomed",
      isBranch: false,
      children: [],
    },
    {
      key: 16063,
      title: "Jaques (Projects) Pienaar",
      isBranch: false,
      children: [],
    },
    {
      key: 16384,
      title: "Konosoang (compliance) Gaosenkwe",
      isBranch: false,
      children: [],
    },
    {
      key: 16488,
      title: "Jayson (HR) Robinson",
      isBranch: false,
      children: [],
    },
    {
      key: 16702,
      title: "Cornel (Sales & Service RBB North) Wentzel",
      isBranch: false,
      children: [],
    },
    {
      key: 16710,
      title: "Kerry (Segment) Carter",
      isBranch: false,
      children: [],
    },
    {
      key: 16759,
      title: "Richard (SBS-RM) Douman",
      isBranch: false,
      children: [],
    },
    { key: 19592, title: "Arthi (MIS) Singh", isBranch: false, children: [] },
    {
      key: 19781,
      title: "Ravikesh (RRB) Kalicharran",
      isBranch: false,
      children: [],
    },
    { key: 19877, title: "Magesh Pillay", isBranch: false, children: [] },
    {
      key: 19918,
      title: "EVERETT (Lean) FOSTER",
      isBranch: false,
      children: [],
    },
    {
      key: 19940,
      title: "Tebogo (Risk) Mokubung",
      isBranch: false,
      children: [],
    },
    {
      key: 20254,
      title: "Nicole (SSM) Harrison",
      isBranch: false,
      children: [],
    },
    { key: 20362, title: "Milton  (C&R) Nkosi", isBranch: false, children: [] },
    {
      key: 20399,
      title: "Cassandra (Distribution) Naidoo",
      isBranch: false,
      children: [],
    },
    {
      key: 20582,
      title: "Chantal (Card) Van den Berg",
      isBranch: false,
      children: [],
    },
    {
      key: 21017,
      title: "Kruger (MI) Pretorius",
      isBranch: false,
      children: [],
    },
    {
      key: 21020,
      title: "Jason (CARD) Mc Kenzie",
      isBranch: false,
      children: [],
    },
    {
      key: 21071,
      title: "CJ  (RRB) Van der Merwe ",
      isBranch: false,
      children: [],
    },
    {
      key: 21184,
      title: "Zimkhita (CE) Ngzingani",
      isBranch: false,
      children: [],
    },
    { key: 21290, title: "Dennis (BIS) Srp", isBranch: false, children: [] },
    {
      key: 21558,
      title: "Akhona (MIS) Matshaya",
      isBranch: false,
      children: [],
    },
    {
      key: 21647,
      title: "Mpho (NSSA) Mabusela",
      isBranch: false,
      children: [],
    },
    {
      key: 21653,
      title: "Linda (process engineer) Makhowane",
      isBranch: false,
      children: [],
    },
    {
      key: 21668,
      title: "Simone (Segment) Harris",
      isBranch: false,
      children: [],
    },
    { key: 21694, title: "Richard Bentheim", isBranch: false, children: [] },
    { key: 21803, title: "Chantal (OD) Ottino", isBranch: false, children: [] },
    { key: 22253, title: "Zamo (RRB) Nkosi", isBranch: false, children: [] },
    {
      key: 22311,
      title: "Renier (NS&SM RRB) Posthumus",
      isBranch: false,
      children: [],
    },
    { key: 22322, title: "Moira (NSSM) Paddey", isBranch: false, children: [] },
    {
      key: 22858,
      title: "Christina (Sales&Retention) Pieterse",
      isBranch: false,
      children: [],
    },
    {
      key: 23115,
      title: "Michel (Card) Gordon",
      isBranch: false,
      children: [],
    },
    {
      key: 23158,
      title: "Prabashanee (NIC) Govender",
      isBranch: false,
      children: [],
    },
    { key: 25389, title: "Nivesh Pranjivan", isBranch: false, children: [] },
    {
      key: 26599,
      title: "Kumbirai (Segment) Kowo ",
      isBranch: false,
      children: [],
    },
    {
      key: 26758,
      title: "Ray (Forensics) Boucher",
      isBranch: false,
      children: [],
    },
    {
      key: 26896,
      title: "Dalene (MIS) Alberts",
      isBranch: false,
      children: [],
    },
    { key: 26989, title: "Mariaan (OD) Goetz", isBranch: false, children: [] },
    { key: 27081, title: "ZEKE MORGAN (OD)", isBranch: false, children: [] },
    { key: 27280, title: "Juan (RRB) Human", isBranch: false, children: [] },
    { key: 27428, title: "Karen (OPS) Krieger", isBranch: false, children: [] },
    {
      key: 27432,
      title: "Alet (RSM Card) Basson",
      isBranch: false,
      children: [],
    },
    {
      key: 27744,
      title: "Lindile (BIS) Madlanga",
      isBranch: false,
      children: [],
    },
    {
      key: 27897,
      title: "Larry (Prod Invest) Arendse",
      isBranch: false,
      children: [],
    },
    { key: 27995, title: "Thapelo (RRB) Tsiu", isBranch: false, children: [] },
    { key: 28246, title: "Deepa (MIS) Vallabh", isBranch: false, children: [] },
    {
      key: 31132,
      title: "Shantell (HL) Mohammed",
      isBranch: false,
      children: [],
    },
    {
      key: 31148,
      title: "Luria (SSM National) Bothma",
      isBranch: false,
      children: [],
    },
    { key: 31373, title: "Idris (BSM) Bakus", isBranch: false, children: [] },
    {
      key: 31390,
      title: "Phakiso (MIS) Sekhosana",
      isBranch: false,
      children: [],
    },
    {
      key: 31686,
      title: "Viren - 161896 Viranna",
      isBranch: false,
      children: [],
    },
    { key: 31759, title: "Samantha Reddy", isBranch: false, children: [] },
    {
      key: 31963,
      title: "Veronica (C&R) Kgaladi",
      isBranch: false,
      children: [],
    },
    {
      key: 32037,
      title: "Lorraine (Risk) Mola",
      isBranch: false,
      children: [],
    },
    {
      key: 32134,
      title: "Zwelithini (Card) Mako",
      isBranch: false,
      children: [],
    },
    {
      key: 33141,
      title: "Katlego (Strategy distribtuion) Loeto",
      isBranch: false,
      children: [],
    },
    {
      key: 33142,
      title: "Sabelo (Client Coverage) Mtolo",
      isBranch: false,
      children: [],
    },
    { key: 33144, title: "Ndidzu (HL) Muntswu", isBranch: false, children: [] },
    {
      key: 33480,
      title: "Sibusiso (MI) Lubambo",
      isBranch: false,
      children: [],
    },
    { key: 33731, title: "Dirk (PL) Louw", isBranch: false, children: [] },
    {
      key: 33743,
      title: "Christo (CARD data) Maritz",
      isBranch: false,
      children: [],
    },
    { key: 35795, title: "IAN (Risk) DE BRUYN", isBranch: false, children: [] },
    {
      key: 35938,
      title: "Shubnum Suleman (RISK)",
      isBranch: false,
      children: [],
    },
    { key: 36937, title: "Keeran (Risk) Singh", isBranch: false, children: [] },
    { key: 37064, title: "Natasha (SSB) Singh", isBranch: false, children: [] },
    {
      key: 37170,
      title: "Pfarelo (CSS) Ramosibudi",
      isBranch: false,
      children: [],
    },
    {
      key: 37193,
      title: "Robyn (Finance) Clark",
      isBranch: false,
      children: [],
    },
    {
      key: 37198,
      title: "Justice Sambo (Risk Monitoring)",
      isBranch: false,
      children: [],
    },
    {
      key: 39016,
      title: "Mabitsela (MIS) Nkgoeng",
      isBranch: false,
      children: [],
    },
    {
      key: 39790,
      title: "Sizwe (RIsk) Khumalo",
      isBranch: false,
      children: [],
    },
    {
      key: 40007,
      title: "Phumzile (SBS-M) Ngobeni",
      isBranch: false,
      children: [],
    },
    {
      key: 40299,
      title: "Nthabiseng (CE) Mohanoe",
      isBranch: false,
      children: [],
    },
    { key: 40583, title: "Mariana (BIS) Maas", isBranch: false, children: [] },
    {
      key: 40630,
      title: "Riyadh (digital) Maheter",
      isBranch: false,
      children: [],
    },
    {
      key: 40841,
      title: "Keshren (MIS) Naicker",
      isBranch: false,
      children: [],
    },
    {
      key: 41186,
      title: "Lee (NIC Finance) King",
      isBranch: false,
      children: [],
    },
    {
      key: 41365,
      title: "Ravi (Product&Pricing) Moodley ",
      isBranch: false,
      children: [],
    },
    { key: 41612, title: "Sithembiso Khawula", isBranch: false, children: [] },
    {
      key: 41796,
      title: "Dino (MFC) Ramparsad",
      isBranch: false,
      children: [],
    },
    {
      key: 41820,
      title: "Livhuhani (FInance) Theka",
      isBranch: false,
      children: [],
    },
    {
      key: 41904,
      title: "Koen (Finance) Marinus",
      isBranch: false,
      children: [],
    },
    {
      key: 41905,
      title: "Rashica (BIS) Mistry",
      isBranch: false,
      children: [],
    },
    {
      key: 42314,
      title: "Chantel (Redscreen)  Wentink",
      isBranch: false,
      children: [],
    },
    { key: 42878, title: "SQS Test User", isBranch: false, children: [] },
    { key: 43302, title: "Tester 5 M (Mobile)", isBranch: false, children: [] },
    {
      key: 45868,
      title: "Dietloff Van Heerden",
      isBranch: false,
      children: [],
    },
    { key: 46496, title: "Pamela  Maharaj", isBranch: false, children: [] },
    { key: 47066, title: "Bradley (TIP) Reddy", isBranch: false, children: [] },
    {
      key: 48825,
      title: "Vincent (Finance) Masilo",
      isBranch: false,
      children: [],
    },
    {
      key: 48891,
      title: "Linda (BIS) Hlongwane",
      isBranch: false,
      children: [],
    },
    {
      key: 49153,
      title: "Tshepho (Distribution) Langa",
      isBranch: false,
      children: [],
    },
    {
      key: 49399,
      title: "Natalia (TM-RRB) Meyer",
      isBranch: false,
      children: [],
    },
    {
      key: 49651,
      title: "Samantha (C&R) George",
      isBranch: false,
      children: [],
    },
    {
      key: 49666,
      title: "Khulekani (Sales&Retention) Sibiya",
      isBranch: false,
      children: [],
    },
    { key: 51974, title: "Adrie (OPS) Louw", isBranch: false, children: [] },
    {
      key: 52073,
      title: "Brian (Branch) Duguid",
      isBranch: false,
      children: [],
    },
    {
      key: 52123,
      title: "Michael (Risk) Davids",
      isBranch: false,
      children: [],
    },
    {
      key: 52126,
      title: "Colette (RRB) Harris",
      isBranch: false,
      children: [],
    },
    {
      key: 52413,
      title: "Grace (RRB) Govender",
      isBranch: false,
      children: [],
    },
    {
      key: 52640,
      title: "Heather (Process) Van Straaten",
      isBranch: false,
      children: [],
    },
    {
      key: 52786,
      title: "Bhavna (Risk) Makkan",
      isBranch: false,
      children: [],
    },
    {
      key: 52849,
      title: "Weena (Projects) Botha",
      isBranch: false,
      children: [],
    },
    {
      key: 53421,
      title: "Mamanyana (Monitoring) Segatle",
      isBranch: false,
      children: [],
    },
    { key: 53963, title: "Katy  Sonekus", isBranch: false, children: [] },
    {
      key: 54083,
      title: "Johan (Finance)  Scheepers",
      isBranch: false,
      children: [],
    },
    { key: 54160, title: "Jingles (BS) Nyathi", isBranch: false, children: [] },
    {
      key: 54296,
      title: "Janice (OD) Govender",
      isBranch: false,
      children: [],
    },
    {
      key: 54297,
      title: "Andreas (MIS) Richter",
      isBranch: false,
      children: [],
    },
    {
      key: 54428,
      title: "Vishal (MIS) Biseswar",
      isBranch: false,
      children: [],
    },
    {
      key: 54541,
      title: "Bharti (Finance) Sham",
      isBranch: false,
      children: [],
    },
    { key: 54737, title: "Noelle (TP) Moning ", isBranch: false, children: [] },
    {
      key: 54776,
      title: "Cheryl  (NSSA) Pillay (Oehely)",
      isBranch: false,
      children: [],
    },
    {
      key: 55868,
      title: "Tumelo (CIA) Mangadi",
      isBranch: false,
      children: [],
    },
    {
      key: 55869,
      title: "Vilen (MIS)  Moodley",
      isBranch: false,
      children: [],
    },
    { key: 55905, title: "Tas (MIS) Singh", isBranch: false, children: [] },
    { key: 56352, title: "Sharon (OPS) Steyn", isBranch: false, children: [] },
    {
      key: 56367,
      title: "Tony (RRB) Rosenzweig",
      isBranch: false,
      children: [],
    },
    {
      key: 56514,
      title: "Arina ( RRB Compliance) Kamffer",
      isBranch: false,
      children: [],
    },
    {
      key: 56648,
      title: "Rachel (Risk) Matojane",
      isBranch: false,
      children: [],
    },
    { key: 56665, title: "Nellie (C&R) Symons", isBranch: false, children: [] },
    { key: 56667, title: "Rufus (MIS) Doolabh", isBranch: false, children: [] },
    {
      key: 56781,
      title: "Anna-Marie (MIS) Rautenbach",
      isBranch: false,
      children: [],
    },
    {
      key: 56790,
      title: "Benita Theron (RISK)",
      isBranch: false,
      children: [],
    },
    {
      key: 56972,
      title: "Monica Van Noordwyk (Risk monitoring)",
      isBranch: false,
      children: [],
    },
    {
      key: 57002,
      title: "Elizabeth (OPS) Grant",
      isBranch: false,
      children: [],
    },
    {
      key: 57193,
      title: "Wellington (NIR) Sikweqe",
      isBranch: false,
      children: [],
    },
    {
      key: 57299,
      title: "Rentia (Finance) Du Toit",
      isBranch: false,
      children: [],
    },
    { key: 57309, title: "Joyce Mangole", isBranch: false, children: [] },
    { key: 57359, title: "Thinus (MFC) Keller", isBranch: false, children: [] },
    {
      key: 59140,
      title: "Kamani (RBS System Sup) Naidoo",
      isBranch: false,
      children: [],
    },
    {
      key: 59157,
      title: "Shaheed (TIP & Forex) Farred",
      isBranch: false,
      children: [],
    },
    {
      key: 59192,
      title: "Gift (projects) Masemola",
      isBranch: false,
      children: [],
    },
    {
      key: 59216,
      title: "Patrick (Finance) Kafuko",
      isBranch: false,
      children: [],
    },
    {
      key: 59355,
      title: "Ed (Segment) Chanetsa",
      isBranch: false,
      children: [],
    },
    {
      key: 59658,
      title: "Refilwe (MIS) Tlholo",
      isBranch: false,
      children: [],
    },
    {
      key: 60174,
      title: "Benedict (MIS) Mogorosi",
      isBranch: false,
      children: [],
    },
    {
      key: 60228,
      title: "Zak (Segment) Mzwazwa",
      isBranch: false,
      children: [],
    },
    {
      key: 60232,
      title: "Ntebaleng (Segment) Makgalemele",
      isBranch: false,
      children: [],
    },
    {
      key: 60631,
      title: "Akhona Panyaza (RISK)",
      isBranch: false,
      children: [],
    },
    { key: 60994, title: "Kaja (CARD) Mulumba", isBranch: false, children: [] },
    {
      key: 62443,
      title: "Dietrich (Risk) Vivier",
      isBranch: false,
      children: [],
    },
    {
      key: 62742,
      title: "Willie (HR) Labuschagne",
      isBranch: false,
      children: [],
    },
    {
      key: 62758,
      title: "Dorrie (Risk) Geddes",
      isBranch: false,
      children: [],
    },
    {
      key: 62794,
      title: "Bailey (MFC) Govender",
      isBranch: false,
      children: [],
    },
    { key: 62826, title: "Charmain  Barnardo", isBranch: false, children: [] },
    {
      key: 62982,
      title: "Azraa (Conformance) Vangeria",
      isBranch: false,
      children: [],
    },
    {
      key: 62983,
      title: "Juanita (Process) Vermaak",
      isBranch: false,
      children: [],
    },
    {
      key: 63126,
      title: "Yvonne (Change Managment) Van Niekerk",
      isBranch: false,
      children: [],
    },
    {
      key: 63169,
      title: "Amanda (RRB) Jansen Van Rensburg",
      isBranch: false,
      children: [],
    },
    {
      key: 63410,
      title: "Elmarie (Branch) Claassen",
      isBranch: false,
      children: [],
    },
    {
      key: 63618,
      title: "RICHARD (C&R) MAPHIRI (Risk Monitoring)",
      isBranch: false,
      children: [],
    },
    {
      key: 63768,
      title: "Daphne (NSM RRB & BB) Steyn",
      isBranch: false,
      children: [],
    },
    {
      key: 63778,
      title: "Debbie (BIS) Lombard",
      isBranch: false,
      children: [],
    },
    {
      key: 63799,
      title: "Brendon Van Huyssteen (National) ",
      isBranch: false,
      children: [],
    },
    {
      key: 63865,
      title: "Lesego (ROA) Tlailane",
      isBranch: false,
      children: [],
    },
    {
      key: 64069,
      title: "Thabo (Segment) Hollo",
      isBranch: false,
      children: [],
    },
    {
      key: 64106,
      title: "Monica (TIP) Esteves",
      isBranch: false,
      children: [],
    },
    {
      key: 64927,
      title: "Sasha (using for testing) Boucher(do not delete)",
      isBranch: false,
      children: [],
    },
    {
      key: 64972,
      title: "Vuyo (Digital) Dyanti",
      isBranch: false,
      children: [],
    },
    { key: 65230, title: "Somesh (MIS) Naidoo", isBranch: false, children: [] },
    {
      key: 65828,
      title: "Praveen Reddy (EMI) Vendidandi",
      isBranch: false,
      children: [],
    },
    {
      key: 65833,
      title: "Michael (Head Finance) Stanley",
      isBranch: false,
      children: [],
    },
    { key: 65933, title: "Michael Maree", isBranch: false, children: [] },
    { key: 65935, title: "Marlon Vorster", isBranch: false, children: [] },
    { key: 65936, title: "Ashley Bierman", isBranch: false, children: [] },
    {
      key: 65944,
      title: "Champion (CARD) Ntulini",
      isBranch: false,
      children: [],
    },
  ],
  errorMessage: null,
  timeGenerated: "2020-04-16T15:21:29.7202295Z",
};

const db = {
  "21469": { result: [] },
  "22031": { result: [] },
  "22033": {
    result: [
      {
        key: 25524,
        title: "Tshepo (SC) Ndlovu ",
        isBranch: false,
        children: [],
      },
      {
        key: 35983,
        title: "Cheantelle (SC) Smit",
        isBranch: false,
        children: [],
      },
      {
        key: 65316,
        title: "Martin (SC) Oelofse",
        isBranch: false,
        children: [],
      },
    ],
    errorMessage: null,
    timeGenerated: "2020-04-17T06:27:03.4702335Z",
  },
  "22425": {
    result: [
      { key: 22431, title: "Tshwane", isBranch: true, children: [] },
      { key: 22433, title: "Gauteng East", isBranch: true, children: [] },
      { key: 22436, title: "Gauteng North", isBranch: true, children: [] },
      {
        key: 22441,
        title: "Limpopo & Mpumalanga",
        isBranch: true,
        children: [],
      },
      { key: 22442, title: "Gauteng Central", isBranch: true, children: [] },
      {
        key: 21442,
        title: "Hayder (Distribution) Dalwai",
        isBranch: false,
        children: [],
      },
      {
        key: 52718,
        title: "David (Div North) Schwegmann",
        isBranch: false,
        children: [],
      },
      {
        key: 64598,
        title: "Chantell (Executive PA) Van Eeden",
        isBranch: false,
        children: [],
      },
    ],
    errorMessage: null,
    timeGenerated: "2020-04-17T06:30:01.3058028Z",
  },
  "22436": {
    result: [
      {
        key: 22353,
        title: "Gauteng North & West Mobile Team",
        isBranch: true,
        children: [],
      },
      { key: 22413, title: "SANDTON", isBranch: true, children: [] },
      { key: 22415, title: "FOURWAYS", isBranch: true, children: [] },
      { key: 22416, title: "JHB NORTH", isBranch: true, children: [] },
      {
        key: 2819,
        title: "Brigitte (Prov. Gen. Mngr) Ryder",
        isBranch: false,
        children: [],
      },
      { key: 5274, title: "Dodosie Nyawo", isBranch: false, children: [] },
      {
        key: 5915,
        title: "Coillard (BB Prov. Mngr) Ford",
        isBranch: false,
        children: [],
      },
      {
        key: 7213,
        title: "Thulisile(HR Mngr) Makhathini",
        isBranch: false,
        children: [],
      },
      {
        key: 11279,
        title: "Devi (BSM) Naicker",
        isBranch: false,
        children: [],
      },
      {
        key: 11434,
        title: "Seema (PSM) Nundhlall",
        isBranch: false,
        children: [],
      },
      {
        key: 14899,
        title: "Shafaaz (SP SBS) Shaik",
        isBranch: false,
        children: [],
      },
      {
        key: 19212,
        title: "Wolfie(Trans Banker) Weise",
        isBranch: false,
        children: [],
      },
      { key: 19944, title: "Khotso (SS) Leolo", isBranch: false, children: [] },
      {
        key: 20075,
        title: "Patricia (Trans Banker) Mandla",
        isBranch: false,
        children: [],
      },
      {
        key: 22009,
        title: "Dalton (PA) Earland",
        isBranch: false,
        children: [],
      },
      {
        key: 23143,
        title: "Regina (RRB PM) Gounden",
        isBranch: false,
        children: [],
      },
      {
        key: 27066,
        title: "Wayne (SSM-RRB) Knoesen",
        isBranch: false,
        children: [],
      },
      {
        key: 27589,
        title: "Joe ( RRB SSM) Atti",
        isBranch: false,
        children: [],
      },
      {
        key: 35808,
        title: "Laaiqah (BSM) Alli",
        isBranch: false,
        children: [],
      },
      {
        key: 49345,
        title: "Charles (PL Sales Support) Makama ",
        isBranch: false,
        children: [],
      },
      { key: 63012, title: "Sulaiman Casoo", isBranch: false, children: [] },
      {
        key: 63035,
        title: "Karuna(SSM)(CMS Admin) Roopchund",
        isBranch: false,
        children: [],
      },
      {
        key: 65263,
        title: "Luvo (SSM/CMS Reg Admin) Ndlumbini",
        isBranch: false,
        children: [],
      },
    ],
    errorMessage: null,
    timeGenerated: "2020-04-17T06:31:42.8704927Z",
  },
  "20760": {
    result: [
      {
        key: 3639,
        title: "Krisnie (TLCS) Naidoo",
        isBranch: false,
        children: [],
      },
      {
        key: 5378,
        title: "Ruth (Multi F and Forex) Buthelezi",
        isBranch: false,
        children: [],
      },
      { key: 9781, title: "Hennie (PRB) Homan", isBranch: false, children: [] },
      {
        key: 9782,
        title: "Radiefa(SC) Matthew",
        isBranch: false,
        children: [],
      },
      {
        key: 10381,
        title: "Clayton (Multifunction) Morris",
        isBranch: false,
        children: [],
      },
      {
        key: 14894,
        title: "Phiwe- Multifunctional Hobe",
        isBranch: false,
        children: [],
      },
      {
        key: 18660,
        title: "Thembi (SC) Lukhele",
        isBranch: false,
        children: [],
      },
      {
        key: 20050,
        title: "Ntombizodwa (SBS M) Radebe",
        isBranch: false,
        children: [],
      },
      {
        key: 21266,
        title: "Charlene  - client coach Berning",
        isBranch: false,
        children: [],
      },
      {
        key: 21881,
        title: "Rubeshini - Multifunctional Govender",
        isBranch: false,
        children: [],
      },
      {
        key: 28080,
        title: "Cyril (SBS-M) Mathonsi",
        isBranch: false,
        children: [],
      },
      {
        key: 29309,
        title: "Refilwe - Client coach Tsetlhane",
        isBranch: false,
        children: [],
      },
      {
        key: 37038,
        title: "Julia - Multifunctional Thema",
        isBranch: false,
        children: [],
      },
      {
        key: 49062,
        title: "Nthabiseng (BM) Mohlabasi",
        isBranch: false,
        children: [],
      },
      {
        key: 53883,
        title: "Silindani 80HRS Multi F Mathonsi",
        isBranch: false,
        children: [],
      },
      {
        key: 55719,
        title: "Mfuneko (Multifunctional) Tyatyeka ",
        isBranch: false,
        children: [],
      },
      {
        key: 55730,
        title: "Keitumetse- Pro Pate",
        isBranch: false,
        children: [],
      },
      { key: 60798, title: "Bongi (T/E) July", isBranch: false, children: [] },
      {
        key: 63995,
        title: "Yvonne-Bulk Teller Naidoo",
        isBranch: false,
        children: [],
      },
      {
        key: 65123,
        title: "Morris (TLS) Raphandana",
        isBranch: false,
        children: [],
      },
    ],
    errorMessage: null,
    timeGenerated: "2020-04-17T07:32:11.2718846Z",
  },
};

const searchData = {
  result: [
    { key: 20378, title: "Cleary Park (012)", isBranch: true, children: [] },
    {
      key: 20760,
      title: "Clearwaters Roodepoort (825)",
      isBranch: true,
      children: [],
    },
    {
      key: 22938,
      title: "Boxer Maclear (479) (CLOSED 14/02/2014)",
      isBranch: true,
      children: [],
    },
  ],
  errorMessage: null,
  timeGenerated: "2020-04-16T16:19:18.2821978Z",
};

const StructureURL = "https://localhost:44385/api/Structures";
const SearchURL = "";

export async function GetBranchChildren_B(branchCode, includeEmployees) {
  if (branchCode === 812)
    return new Promise((resolve) => {
      setTimeout(() => resolve(loadData), 1000);
    });
  else
    return new Promise((resolve) => {
      var key = branchCode.toString();
      setTimeout(() => resolve(db[key]), 1000);
    });
}

export async function GetBranchChildren(ParentKey) {
  const url = `${StructureURL}${ParentKey ? `/${ParentKey}` : ""}`;
  let obj = [];
  const response = await fetch(url, {
    method: "GET",
  });
  const json = await response.json();
  if (!ParentKey) {
    json.map((Main) => {
      obj.push({
        key: Main.code,
        title: Main.name,
        children: [],
        dbid: Main.id,
        isBranch: true,
      });
    });
  } else {
    json.childBranches.map((Main) => {
      obj.push({
        key: Main.code,
        title: Main.name,
        children: [],
        dbid: Main.id,
        isBranch: true,
      });
    });
    json.childEmployees.map((Main) => {
      obj.push({
        key: Main.staffNo,
        title: `${Main.firstName} ${Main.lastName}`,
        children: [],
        dbid: Main.id,
        isBranch: false,
      });
    });
  }
  return obj;
}

export async function SearchStructure(searchKey, Channel) {
  return new Promise((resolve) => {
    setTimeout(() => resolve(searchData), 1000);
  });
}

export async function SearchStructure_A(ParentKey) {
  const url = `${SearchURL}${ParentKey}`;
  let obj = [];
  const response = await fetch(url, {
    method: "GET",
  });
  const json = await response.json();
  json.map((Main) => {
    obj.push({
      key: Main.data[1].value,
      title: Main.data[2].value,
      children: [],
      isBranch: Main.data[3].value === "0" ? false : true,
    });
  });
  return new Promise(obj);
}
